version: "3.4"

services:
  api:
    container_name: node-api
    image: node-api
    build:
      context: .
      dockerfile: .docker/dev.dockerfile
    environment:
      PORT: 5000
      MONGO_URL: mongodb://database:27017
      NODE_ENV: dev
    ports:
      - "5000:5000"
    links:
      - database
    depends_on:
      - database
  
  database:
    container_name: database
    image: mongo:4.0.3
    ports:
      - "27017:27017"
